---
#https://github.com/geerlingguy/ansible-role-jenkins/
#https://github.com/jcalazan/ansible-jenkins
- hosts: u16
  become: yes
  tasks:
  #need check
  - name: Install packages and dependencies
    apt: name={{ item }} update_cache=yes state=present
    with_items:
    - default-jdk
    - libfontconfig
    - libffi-dev
    - libncurses5-dev

  - name: Add the Jenkins public GPG key to the apt repo
    apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
           state=present

  - name: Add Jenkins to the trusted sources list
    apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/'
                  update_cache=yes
                  state=present
  - name: Install Jenkins server
    apt: name=jenkins state=present
  
  - name: get contents of file - Jenkins pass
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: pass
    become: true
  - name: Unlock Jenkins password
    debug: var=pass.stdout_lines